### ISSUE TITLE
Slack channel permissions

### ISSUE THREAD

**Issue by MichaelSp** [knative/build-templates#44]
Hi guys.

In the readme you promote the slack channel [knative.slack.com](knative.slack.com) which is locked  to `@google.com, @pivotal.io, @ibm.com, or @redhat.com`. 
On purpose?
 
--
(le me being from `@sap`)

**Comment by sslavic** [comment]
@MichaelSp I think those instructions are just outdated as of recently. See https://github.com/knative/docs/issues/257#issuecomment-407812355

**Comment by MichaelSp** [comment]
got it, thanks
