### ISSUE TITLE
v3 support for the buildpack build template

### ISSUE THREAD

**Issue by jldec** [knative/build-templates#45]
riff would like to move to buildpacks for function builds. Since riff function invokers form the basis for building function images with riff, they are somewhat coupled to the build strategy. Existing invokers provide templates for Dockerfiles which allows them to be used with the Kaniko build template.

It would be beneficial to move to the [V3 buildpack API](https://github.com/buildpack/resources) to simplify the creation of buildpacks for new function invokers.

**Comment by jldec** [comment]
see https://github.com/projectriff/riff/issues/654

**Comment by sclevine** [comment]
In progress here: https://github.com/buildpack/resources/issues/1

**Comment by scothis** [comment]
Fixed by #67 

/close
