### ISSUE TITLE
kaniko template cannot push to gcr

### ISSUE THREAD

**Issue by sebgoa** [knative/build-templates#85]
When you need to define GOOGLE_APPLICATION_CREDENTIALS properly.

the answer is in:

https://github.com/knative/build/issues/450#issuecomment-437116252

**Comment by evankanderson** [comment]
See also https://github.com/GoogleContainerTools/kaniko/issues/392

Based on the debugging in https://github.com/knative/build/issues/450#issuecomment-437116252, it looks like Kaniko no longer uses the docker credential helpers if configured when talking to GCR, and instead looks for other things in other places.

**Comment by sebgoa** [comment]
happy to close this here since there are other issues tracking it.

**Comment by evankanderson** [comment]
Two options are to revert to v0.1.0, or to see if Kaniko can be configured to use the default credential helpers. Putting the files in other locations just for GCR/Kaniko seems fragile.

But we should update the build-template to be working, I can send a PR to downgrade the v0.1.0 image for now.

**Comment by sebgoa** [comment]
I get the pin, but kaniko is already on v0.7.0
you might get other problems by reverting to v0.1.0
